### ISSUE TITLE
Device Twin update should be an async call

### ISSUE THREAD

**Issue by gloveboxes** [Azure-Sphere-DevX/AzureSphereDevX#19]
@bawilless A device twin update had a IoTHubDeviceClient_LL_DoWork at the end that was turning what should be an async call into an sync call. Have removed the call to dowork so a twin update wont force a a sync dowork operation. I believe this is inline with how a twin should operate. The twin update will be picked up by the main IoTHubDeviceClient_LL_DoWork on the 100ms timer in the azure_iot client

**Comment by bawilless** [comment]
I see that this call has been removed/commented out.  Closing this issue as resolved.
