### ISSUE TITLE
Improve IoTHub connection errors

### ISSUE THREAD

**Issue by bawilless** [Azure-Sphere-DevX/AzureSphereDevX#29]
When devices don't connect to the IoTHub the error messages don't usually help the developer understand the root cause of the issue.  It would be great to simulate different failure modes, and make sure that the error messages are meaningful.

For example, if my device has a wifi connection, but the connection is not to the internet devX reports ```ERROR: Current Application not Device Auth Ready```  A beter error message would be ```ERROR: No internet connection, check your network connection"```

**Comment by gloveboxes** [comment]
@bawilless  closed as fixed as suggested
