### ISSUE TITLE
dx_utilities: dx_startThreadDetached, malformed function pointer?

### ISSUE THREAD

**Issue by CraigGabel** [Azure-Sphere-DevX/AzureSphereDevX#50]
I've started to do some work with a unit test framework that had some problems mocking this function.  Is the function pointer here malformed?

https://github.com/Azure-Sphere-DevX/AzureSphereDevX/blob/e521092897696637f1b16905f554a3eb562f48a5/include/dx_utilities.h#L44

**Comment by CraigGabel** [comment]
to clarify, should the prototype be:
`bool dx_startThreadDetached(void (*daemon)(void *), void *arg, char *daemon_name);`

**Comment by CraigGabel** [comment]
well, it does seem that the asterix in front of daemon is optional
it appears the rest of the function pointers in AzureSphereDevX do use this optional asterix

unfortunately, my test [framework](http://www.throwtheswitch.org/) does require it

**Comment by bawilless** [comment]
@gloveboxes, can you comment on this issue/question?  
Thanks,
Brian

**Comment by gloveboxes** [comment]
Hmmm, looking at https://man7.org/linux/man-pages/man3/pthread_create.3.html it seems you are right 😀

I've updated the EdgeDevX version as I can test on my laptop  https://github.com/Azure-Sphere-DevX/EdgeDevX/blob/b8e443f51e437728b0a6b809a2c300cdaa53fb0c/src/dx_utilities.c#L261. 

Tomorrow I'll test on a Sphere to make sure it works as expected.

Thank you!

int pthread_create(pthread_t *restrict thread,
                          const pthread_attr_t *restrict attr,
                          void ***(*start_routine)**(void *),
                          void *restrict arg);

**Comment by gloveboxes** [comment]
@CraigGabel @bawilless 

I've fixed the return type to be dx_startThreadDetached(void *(*daemon)(void *), void *arg, char *daemon_name);

I've tested and pushed the change.

Thanks again!

@bawilless I've also updated the AzureSphereDevX.Examples to use the latest version of AzureSphereDevX lib.

Cheers Dave

**Comment by CraigGabel** [comment]
Thanks for looking into this, Dave! :smiley:
